name: zigbee_2_mqtt_flutter
description: "A Flutter framework for real-time Zigbee2MQTT integration."
version: 0.0.1
homepage: https://azylla.dev/

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mqtt_client: ^10.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pedantic: ^1.9.0
  commitlint_cli: ^0.8.1
  husky: ^0.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
